["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["src"]

[profile.ci.protostar.shared_command_configs]
no_color = true
target = "src/onlydust/imhotep/tests"

["protostar.contracts"]
evm = [
  "./src/onlydust/imhotep/evm.cairo",
]
